Learntest/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app01.srcs.views import departments, myadmin, number, user, account, task, order

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("dbop", views.dbop),

    path("depart/list", departments.depart_list),
    path("depart/add", departments.depart_add),
    path("depart/<int:nid>/edit/", departments.depart_edit),
    path("depart/delete/", departments.depart_delete),

    path("user/list", user.user_list),
    path("user/add", user.user_add),
    path("user/delete/", user.user_delete),
    path("user/<nid>/edit/", user.user_edit),

    path("numbers/list", number.number_list),
    path("numbers/add", number.number_add),
    path("numbers/<int:nid>/edit", number.number_edit),
    path("numbers/delete/", number.number_delete),

    path("myadmin/list", myadmin.myadmin_list),
    path("myadmin/add", myadmin.myadmin_add),
    path("myadmin/<nid>/edit/", myadmin.myadmin_edit),
    path("myadmin/delete/", myadmin.myadmin_delete),
    path("myadmin/<nid>/reset/", myadmin.myadmin_reset_pwd),

    path("login/", account.login),
    path("logout/", account.logout),

    path("task/list", task.task_list),
    path("task/ajax", task.task_ajax),
    path("task/add", task.task_add),

    path("order/list", order.order_list),
    path("task/delete/", task.task_delete),
]

app01/models.py
from django.db import models
# Create your models here.
import datetime


class Department(models.Model):
    """部门表"""
    department_id = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name="部门名", max_length=100, null=True, blank=True, default="")

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """用户表"""
    user_id = models.CharField(verbose_name="角色账号", primary_key=True, max_length=30)
    name = models.CharField(verbose_name="姓名", max_length=30, null=True, blank=True, default="")
    password = models.CharField(verbose_name="角色编码", max_length=64, null=True, blank=True, default="")
    age = models.IntegerField(verbose_name="等级", null=True, blank=True, default=18)
    account = models.DecimalField(verbose_name="摩拉余额", decimal_places=2, max_digits=10, null=True, blank=True,
                                  default=0.0)
    # obj.creat_time.strftime("%Y-%m-%d")
    creat_time = models.DateTimeField(verbose_name="加入日期", null=True, blank=True, default=datetime.datetime.now())
    # django约束
    gender_choices = ((1, "男"), (2, "女"))
    # obj.get_gender_display()获取男女
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices, null=True, blank=True)
    # 数据库外键约束
    # Department.user_set()即可获取部门的所有员工
    department = models.ForeignKey(to="Department", to_field="department_id", related_name="user_set",
                                   verbose_name="委托地区", null=True, blank=True, on_delete=models.SET_NULL)

    # on_delete=models.CASCADE 级联删除

    def __str__(self):
        return self.name


class PhoneNumbers(models.Model):
    mobile = models.CharField(verbose_name="UID", max_length=15)
    price = models.DecimalField(verbose_name="摩拉余额", decimal_places=2, max_digits=12, null=True, blank=True)
    level_choices = (
        (1, "一级"),
        (2, "二级别"),
        (3, "三级别"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1, null=True, blank=True)
    status_choices = (
        (1, "占用"),
        (2, "未占用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2, null=True, blank=True)


class MyAdmin(models.Model):
    id = models.CharField(verbose_name="管理员账号", primary_key=True, max_length=32)
    user_name = models.CharField(verbose_name="管理员名", max_length=32)
    password = models.CharField(verbose_name="管理员密码", max_length=64)
    is_superadmin = models.BooleanField(verbose_name="是否是超级管理员", default=False)
    class Meta:
        verbose_name = "管理员"
        db_table = "管理员表"

    def __str__(self):
        return self.user_name


class Task(models.Model):
    title = models.CharField(verbose_name="标题", max_length=64)
    level_choices = (
        (1, "紧急"),
        (2, "一般"),
        (3, "不紧急"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=2)
    user = models.ForeignKey(verbose_name="负责人", to="UserInfo", to_field="user_id", null=True, blank=True,
                             on_delete=models.SET_NULL)
    detail = models.TextField(verbose_name="详细信息", null=True, blank=True)


class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=64, primary_key=True)
    title = models.CharField(verbose_name="名称", max_length=32, blank=True, null=True)
    price = models.DecimalField(verbose_name="价格", blank=True, null=True, decimal_places=2, max_digits=10)
    status_choices = (
        (1, "待支付"),
        (2, "支付中"),
        (3, "已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, blank=True, null=True)
    admin = models.ForeignKey(verbose_name="管理员", to="MyAdmin", to_field="id",
                              null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(verbose_name="用户", to="UserInfo", to_field="user_id",
                             null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

app01/srcs/views/account.py
from django.http import HttpResponse, request
from django.shortcuts import render, redirect
from django import forms
from app01.utils.md5 import get_md5
from app01.models import MyAdmin


# 用form自定义，也可以用modelform
class LoginForm(forms.Form):
    user_name = forms.CharField(label="用户名", required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "用户名"},))
    password = forms.CharField(label="密码", required=True,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "密码"},
                                                          render_value=True))  # render_value代表刷新不清空
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return get_md5(pwd)


def login(req):
    if req.method == "GET":
        form = LoginForm
        return render(req, "account/login.html", {"form": form})

    form = LoginForm(data=req.POST)
    if form.is_valid():
        adm_obj = MyAdmin.objects.filter(**form.cleaned_data).first()
        if not adm_obj:
            form.add_error("password", "用户名或密码错误")
            return render(req, "account/login.html", {"form": form})
        req.session["info"] = {"id": adm_obj.id, "name": adm_obj.user_name, "is_superadmin": adm_obj.is_superadmin}
        # return HttpResponse("提交成功")
        return redirect("/myadmin/list")
    return render(req, "account/login.html", {"form": form})


def logout(req):
    req.session.clear()
    return redirect("/")

app01/srcs/views/departments.py
from django.shortcuts import render, redirect

from app01.models import Department, UserInfo, PhoneNumbers
from app01.utils.page_nav import PageNav
from app01.srcs.forms.form import NumModelForm, NumModelFormEdit, UserModelForm


def depart_list(request):
    queryset = Department.objects.all()
    content = {
        "queryset": queryset,
    }
    return render(request, "departments/depart_list.html", content)


def depart_add(request):
    if request.method == "GET":
        return render(request, "departments/depart_add.html", )
    else:
        new_title = request.POST.get("new_title")
        Department.objects.create(title=new_title)
        return redirect("/depart/list")


def depart_delete(req):
    nid = req.GET.get("nid")
    Department.objects.filter(department_id=nid).delete()
    return redirect("/depart/list")


def depart_edit(req, nid):
    obj = Department.objects.filter(department_id=nid)
    if req.method == "GET":
        content = {
            "department_id": obj.first().department_id,
            "title": obj.first().title
        }
        return render(req, "departments/depart_edit.html", content)
    else:
        new_title = req.POST.get("new_title")
        obj.update(title=new_title)
        return redirect("/depart/list")

app01/srcs/views/myadmin.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from app01.models import MyAdmin
from app01.utils.page_nav import PageNav
from app01.srcs.forms.form import MyadminForm, MyadminFormEdit, MyadminFormReset

def myadmin_list(req):
    info = req.session.get("info", {})

    search_data = req.GET.get("q", "")
    search_data_dict = {"user_name__contains": search_data} if search_data else {}
    queryset = MyAdmin.objects.filter(**search_data_dict)
    page_nav_obj = PageNav(req, queryset)
    content = {
        "queryset": page_nav_obj.page_queryset,
        "page_nav_string": page_nav_obj.get_html(),
    }
    return render(req, "myadmin/myadmin_list.html", content)

def myadmin_add(req):
    info = req.session.get("info", {})
    if not info.get("is_superadmin"):
        return HttpResponse("无权访问", status=403)

    if req.method == "GET":
        form = MyadminForm()
        return render(req, "change.html", {"form": form, "add_name": "添加管理员"})
    else:
        form = MyadminForm(data=req.POST)
        if form.is_valid():
            form.save()
            return redirect("/myadmin/list")
        else:
            return render(req, "change.html", {"form": form, "title": "添加管理员"})

def myadmin_edit(req, nid):
    info = req.session.get("info", {})
    if not info.get("is_superadmin"):
        return HttpResponse("无权访问", status=403)

    row_obj = MyAdmin.objects.filter(id=nid).first()
    if not row_obj:
        return render(req, "error.html")

    if req.method == "GET":
        form = MyadminFormEdit(instance=row_obj)
        return render(req, "change.html", {"form": form, "title": "编辑管理员"})
    else:
        form = MyadminFormEdit(instance=row_obj, data=req.POST)
        if form.is_valid():
            form.save()
            return redirect("/myadmin/list")
        return render(req, "change.html", {"form": form, "title": "编辑管理员"})

def myadmin_delete(req):
    info = req.session.get("info", {})
    if not info.get("is_superadmin"):
        return HttpResponse("无权访问", status=403)

    nid = req.GET.get("nid")
    MyAdmin.objects.filter(id=nid).delete()
    return redirect("/myadmin/list")

def myadmin_reset_pwd(req, nid):
    info = req.session.get("info", {})
    if not info.get("is_superadmin"):
        return HttpResponse("无权访问", status=403)

    row_obj = MyAdmin.objects.filter(id=nid).first()
    if not row_obj:
        return render(req, "error.html")

    if req.method == "GET":
        form = MyadminFormReset(instance=row_obj)
        return render(req, "change.html", {"form": form, "title": "重置密码"})
    else:
        form = MyadminFormReset(instance=row_obj, data=req.POST)
        if form.is_valid():
            form.save()
            return redirect("/myadmin/list")
        return render(req, "change.html", {"form": form, "title": "重置密码"})

app01/srcs/views/number.py
from django.shortcuts import render, redirect

from app01.models import Department, UserInfo, PhoneNumbers
from app01.utils.page_nav import PageNav
from app01.srcs.forms.form import NumModelForm, NumModelFormEdit, UserModelForm


def number_list(req):
    search_data_dict = {}
    search_data = req.GET.get("q", "")
    page = int(req.GET.get("page", "1"))  # 第二个参数表示默认数值
    start_page = page-5
    end_page = page+5

    if search_data:
        search_data_dict["mobile__contains"] = search_data
        # mobile__contains==xx 作为filter参数表示字符串包含xx 类似的 还有 __gt __lte __startwith
    queryset = PhoneNumbers.objects.filter(**search_data_dict).order_by("-level")
    # 相当于 order by level desc ,   queryset切片可以越界但要为正数

    page_nav_obj = PageNav(req, queryset)
    page_queryset = page_nav_obj.page_queryset
    page_nav_string = page_nav_obj.get_html()
    content = {
        "queryset": page_queryset,
        "search_data": search_data,
        "page_nav_string": page_nav_string,
    }
    return render(req, "numbers/num_list.html", content)


def number_add(req):
    if req.method == "GET":
        form = NumModelForm()
        content = {
            "form": form
        }
        return render(req, "numbers/num_add.html", content)
    form = NumModelForm(data=req.POST)
    if form.is_valid():
        # form.instance.字段名 = 手动赋值
        form.save()
        return redirect("/numbers/list")
    return render(req, "numbers/num_add.html", {"form": form})


def number_edit(req, nid):
    obj_row = PhoneNumbers.objects.filter(id=nid).first()
    if req.method == "GET":
        form = NumModelFormEdit(instance=obj_row)
        return render(req, "numbers/num_edit.html", {"form": form})
    form = NumModelFormEdit(instance=obj_row, data=req.POST)
    if form.is_valid():
        form.save()
        return redirect("/numbers/list")
    return render(req, "numbers/num_edit.html", {"form": form})


def number_delete(req):
    nid = req.GET.get("nid")
    PhoneNumbers.objects.filter(id=nid).delete()
    return redirect("/numbers/list")

app01/srcs/views/order.py
from django.shortcuts import render, redirect
from django import forms
from app01.models import Order


def order_list(request):
    content={}
    return render(request,"order/order_list.html",content)

app01/srcs/views/task.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from app01 import models
from app01.utils.bootstrap_modelform import BootstrapModelForm
from app01.models import Task
from app01.utils.page_nav import PageNav


class TaskModelForm(BootstrapModelForm):
    class Meta:
        model = models.Task
        fields = "__all__"


def task_list(request):
    print("1")
    print(request)
    queryset = models.Task.objects.all().order_by("-id")
    page_nav_obj = PageNav(request, queryset)
    page_queryset = page_nav_obj.page_queryset
    page_nav_string = page_nav_obj.get_html()
    form = TaskModelForm()
    content = {"form": form,
               "queryset": page_queryset,
               "page_nav_string": page_nav_string, }
    return render(request, "task/task_list.html", content)


import json
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt  # 免除csrf_token认证，就可发post
def task_ajax(request):
    print(request.GET)
    print(request.POST)
    json_string = json.dumps(request.GET)
    return HttpResponse(json_string)


@csrf_exempt  # 免除csrf_token认证，就可发post
def task_add(request):
    print(1)
    form = TaskModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        data_dict = {"status": True}
        return HttpResponse(json.dumps(data_dict))
    data_dict = {"status": False, "error": form.errors}
    return HttpResponse(json.dumps(data_dict, ensure_ascii=False))


# def task_edit(req, nid):
#     obj_row = Task.objects.filter(id=nid).first()
#     if req.method == "GET":
#         form = NumModelFormEdit(instance=obj_row)
#         return render(req, "numbers/num_edit.html", {"form": form})
#     form = NumModelFormEdit(instance=obj_row, data=req.POST)
#     if form.is_valid():
#         form.save()
#         return redirect("/numbers/list")
#     return render(req, "numbers/num_edit.html", {"form": form})

def task_delete(req):
    nid = req.GET.get("nid")
    Task.objects.filter(id=nid).delete()
    return redirect("/task/list")

app01/views.py
from django.shortcuts import render, redirect, HttpResponse


# Create your views here.

def index(req):
    return render(req, "index.html")


def dbop(req):
    import random
    from app01.models import UserInfo, PhoneNumbers
    for i in range(100, 300):
            number = random.randint(1000000000, 9999999999)
            UserInfo.objects.create(user_id=str(i))
            PhoneNumbers.objects.create(mobile=number)
    return HttpResponse("done")

app01/templates/numbers/num_add.html
{% extends "layout.html" %}

{% block content %}
<br>
<div>
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item list-group-item-dark">
                <i class="bi bi-calendar2-event-fill"></i>
                <strong>添加账号</strong>
            </li>
            <li class="list-group-item">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label>{{ field.label }}</label> {# .label表示verbose_name字段 #}
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                <div style="margin: 10px">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
                </form>

            </li>
        </ul>
    </div>
</div>

{% endblock %}

app01/templates/numbers/num_edit.html
{% extends "layout.html" %}

{% block content %}
<br>
<div>
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item list-group-item-dark">
                <i class="bi bi-calendar2-event-fill"></i>
                <strong>编辑账号</strong>
            </li>
            <li class="list-group-item">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label>{{ field.label }}</label> {# .label表示verbose_name字段 #}
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                <div style="margin: 10px">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
                </form>

            </li>
        </ul>
    </div>
</div>

{% endblock %}

app01/templates/numbers/num_list.html
{% extends "layout.html" %}

{% load static %}  <!-- 加载静态文件 -->

{% block content %}
<style>
    .container-background {
        background: url('{% static "img/3.jpg" %}') no-repeat center center fixed;
        background-size: cover; /* 覆盖整个容器 */
        position: relative; /* 相对定位，为覆盖层做准备 */
        height: 100vh; /* 设置背景区域至少覆盖整个视口高度 */
        color: white; /* 设置文本颜色为白色以增强可读性 */
    }
    .overlay { /* 覆盖层样式 */
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0, 0, 0, 0.5); /* 半透明覆盖层 */
        z-index: 1; /* 确保覆盖层在背景图片之上 */
    }
    .container { /* 调整内容的容器 */
        position: relative; /* 相对定位，确保内容在覆盖层之上 */
        z-index: 2; /* 确保内容的层级高于覆盖层 */
        padding: 20px; /* 增加一些内边距 */
    }
</style>
<div class="container-background">
    <div class="overlay"></div> <!-- 添加覆盖层 -->
    <div class="container">
        <div class="row">
            <div class="col-md-7 col-sm-4">
                <a class="btn btn-success" style="margin: 10px" href="/numbers/add" target="_blank">
                    <i class="bi bi-plus-circle-fill"></i> 新建账号
                </a>
            </div>
            <div class="col-md-5 col-sm-8">
                <form method="get">
                    <div class="d-flex flex-row">
                        <input class="form-control me-2" type="search" name="q" value="{{ search_data }}" style="margin: 10px" placeholder="搜索" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit" style="margin: 10px; width: 100px"><strong>搜索</strong></button>
                    </div>
                </form>
            </div>
        </div>

        <ul class="list-group">
            <li class="list-group-item list-group-item-dark">
                <i class="bi bi-calendar2-event-fill"></i>
                <strong>账号列表</strong>
            </li>
            <li class="list-group-item">
                <table class="table">
                    <thead>
                        <tr>
                          <th scope="col">ID</th>
                          <th scope="col">UID</th>
                          <th scope="col">摩拉余额</th>
                          <th scope="col">级别</th>
                          <th scope="col">状态</th>
                          <th scope="col">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in queryset %}
                        <tr>
                            <th scope="row">{{ obj.id }}</th>
                            <td>{{ obj.mobile }}</td>
                            <td>{{ obj.price }}</td>
                            <td>{{ obj.get_level_display }}</td>
                            <td>{{ obj.get_status_display }}</td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="/numbers/{{ obj.id }}/edit">编辑</a>
                                <a class="btn btn-danger btn-sm" href="/numbers/delete/?nid={{ obj.id }}">删除</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </li>
        </ul>
        <div style="display: flex; justify-content: center;"> <!-- 居中 -->
            <nav aria-label="Page navigation example" style="margin: 10px">
                <ul class="pagination">
                    {{ page_nav_string }}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}